### ISSUE TITLE
permissions to retrieve billing

### ISSUE THREAD

**Issue by dpark01** [dnanexus-rnd/dxWDL#70]
Hi,

I created a dedicated user to build WDL workflows with dxWDL, but dxWDL is giving me the following warning message during compile:

> Warning: insufficient permissions to retrieve the instance price list. This will result in suboptimal machine choices, incurring higher costs when running workflows.

The user I created has the following permissions in my org:
- MEMBER (not ADMIN)
- BILLING ALLOWED
- Shared Projects Access: NOT ALLOWED
- APP ACCESS ALLOWED

Do I have to grant this user shared projects access to see the instance price list? Why isn't "BILLING ALLOWED" sufficient permission to retrieve the price list?

**Comment by orodeh** [comment]
There are limitations on who can access the price list for a project, which is what dxWDL needs to get the cheapest instance for a particular spec (disk size, num cpus, etc.).

You need to be able to do a `describeUser` API call, in order to get this list. If you can't, there is a suboptimal algorithm that will make the instance type choices without access to the price list. 

I am pretty sure you need to be an ADMIN for this. Even CONTRIBUTE access isn't sufficient. @mlin, please correct me if I'm mistaken here.

**Comment by dpark01** [comment]
Do you mean org admin or project admin?

**Comment by orodeh** [comment]
Project admin should suffice.

**Comment by dpark01** [comment]
Hm, admin still seems a bit heavy-handed for such read-only information that doesn't seem so privileged (shouldn't anyone who can incur charges be able to see the rates ahead of time?). I may lean towards just specifying dx_instance_type hints whenever the resource requirements are non-trivial. Travis has an API token for this user, and while I'm okay with it incurring compute charges on DNAnexus, I don't feel it should have the authority to delete the dx project entirely.
